---
cert_file: /etc/ssl/certs/ca-certificates.crt
hostname: int-www.example.com
origin: example.com
my_network: 127.0.0.1
src_main: ../templates/postfix.cnf.j2
dest_main: /etc/postfix/main.cf
src_pass: ../templates/sasl_passwd.j2
dest_pass: /etc/postfix/sasl_passwd
src_relay: ../templates/sender_relay.j2
dest_relay: /etc/postfix/sender_relay

