---
- name: Create Kafka SSL directory
  file:
    path: /etc/ssl/certs/kafka
    state: directory
    mode: '0750'
    owner: kafka
    group: kafka

- name: Generate Kafka private key
  openssl_privatekey:
    path: /etc/ssl/private/kafka.key
    owner: kafka
    group: kafka
    mode: '0640'

- name: Generate Kafka CSR
  openssl_csr:
    path: /tmp/kafka.csr
    privatekey_path: /etc/ssl/private/kafka.key
    common_name: "{{ inventory_hostname }}"
    subject_alt_name: "DNS:{{ inventory_hostname }}"
    owner: kafka
    group: kafka

- name: Generate Kafka certificate
  openssl_certificate:
    path: /etc/ssl/certs/kafka.crt
    csr_path: /tmp/kafka.csr
    ownca_path: /etc/ssl/certs/kafka-ca.crt
    ownca_privatekey_path: /etc/ssl/private/kafka-ca.key
    provider: ownca
    owner: kafka
    group: kafka

- name: Create Kafka keystore
  community.general.java_keystore:
    name: kafka
    certificate: /etc/ssl/certs/kafka.crt
    private_key: /etc/ssl/private/kafka.key
    password: "{{ kafka_tls_keystore_password }}"
    dest: /etc/ssl/certs/kafka.keystore.jks
    owner: kafka
    group: kafka

- name: Create Kafka truststore
  community.general.java_keystore:
    name: kafka-truststore
    certificates: /etc/ssl/certs/kafka-ca.crt
    password: "{{ kafka_tls_truststore_password }}"
    dest: /etc/ssl/certs/kafka.truststore.jks
    owner: kafka
    group: kafka
