---
- name: Create Zookeeper keystore directory
  file:
    path: /etc/ssl/certs/zookeeper
    state: directory
    mode: '0750'
    owner: zookeeper
    group: zookeeper

- name: Generate Zookeeper keypair
  openssl_privatekey:
    path: /etc/ssl/private/zookeeper.key
    owner: zookeeper
    group: zookeeper
    mode: '0640'

- name: Generate Zookeeper CSR
  openssl_csr:
    path: /tmp/zookeeper.csr
    privatekey_path: /etc/ssl/private/zookeeper.key
    common_name: "{{ inventory_hostname }}"
    subject_alt_name: "DNS:{{ inventory_hostname }}"
    owner: zookeeper
    group: zookeeper

- name: Generate Zookeeper certificate
  openssl_certificate:
    path: /etc/ssl/certs/zookeeper.crt
    csr_path: /tmp/zookeeper.csr
    ownca_path: /etc/ssl/certs/kafka-ca.crt
    ownca_privatekey_path: /etc/ssl/private/kafka-ca.key
    provider: ownca
    owner: zookeeper
    group: zookeeper

- name: Create Zookeeper keystore
  community.general.java_keystore:
    name: zookeeper
    certificate: /etc/ssl/certs/zookeeper.crt
    private_key: /etc/ssl/private/zookeeper.key
    password: "{{ zookeeper_tls_keystore_password }}"
    dest: /etc/ssl/certs/zookeeper.keystore.jks
    owner: zookeeper
    group: zookeeper

- name: Create Zookeeper truststore
  community.general.java_keystore:
    name: zookeeper-truststore
    certificates: /etc/ssl/certs/kafka-ca.crt
    password: "{{ zookeeper_tls_truststore_password }}"
    dest: /etc/ssl/certs/zookeeper.truststore.jks
    owner: zookeeper
    group: zookeeper
