---
- name: restart zookeeper
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: reload zookeeper
  systemd:
    name: zookeeper
    state: reloaded
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
