---
  - name: Install MySQL
    apt: pkg={{ item }} state=present update_cache=true
    with_items:
    - mysql-server-5.7
    - python-mysqldb
    - python-pip
    - python-dev
    - libmysqlclient-dev

  - name: Change MySQL root Password
    mysql_user: name={{ login_user }} password={{ login_password }} check_implicit_admin=yes login_user={{ login_user }} login_password="" state=present
    ignore_errors: yes

  - name: Create Database
    mysql_db: name={{ db_name }} state=present login_user={{ login_user }} login_password={{ login_password }}

  - name: Add Deploy DB User and Allow Access to the Server
    mysql_user: name={{ db_user }} password={{ db_password }} host="localhost" priv='{{ db_name }}.*:ALL,GRANT' check_implicit_admin=yes login_user={{ login_user }} login_password={{ login_password }} state=present
