- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update APT Cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      ignore_errors: True
      async: 60
      poll: 60

    - name: Upgrade Packages
      apt: upgrade=dist force_apt_get=yes

    - name: Remove dependencies that are no longer required
      command: apt-get -y autoremove

    - name: Remove useless packages from the cache
      command: apt-get -y autoclean

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no