---
  - name: Install Nginx 1.10.x
    apt: pkg=nginx state=installed update_cache=true

  - name: Copy Nginx Sites v1
    template: src={{ src_nginx_conf_dir }}/site1.j2 dest={{ dest_nginx_conf_dir }}/{{ item.server_name }}.conf backup=yes
    with_items: "{{ nginx_vhosts }}"

  - name: Copy Nginx Sites v2
    template: src={{ src_nginx_conf_dir }}/site2.j2 dest={{ dest_nginx_conf_dir }}/{{ item.server_name2 }}.conf backup=yes
    with_items: "{{ nginx_vhosts2 }}"

  - name: Link all the Websites in Nginx sites-available
    file: src={{ dest_nginx_conf_dir }}/{{ item }}.conf dest={{ nginx_enabled_dir }}/{{ item }}.conf state=link force=yes
    with_items: "{{ domains }}"

  - name: Copy SSL PEM
    copy: src={{ ssl_pem_src }} dest={{ ssl_pem_dest }}

  - name: Copy SSL Key
    copy: src={{ ssl_key_src }} dest={{ ssl_key_dest }}
