---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-11-jdk
    - curl
    - wget
    - netcat
    - net-tools

- name: Create base directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ log_dir }}"
    - "{{ data_dir }}"
