---
  - name: Install Postfix
    apt: pkg=postfix state=installed update_cache=true

  - name: Copy Postfix Configuration
    template: src={{ item.source }} dest={{ item.destination }} backup=yes
    with_items:
    - { source: "{{ src_main }}", destination: "{{ dest_main }}" }
    - { source: "{{ src_pass }}", destination: "{{ dest_pass }}" }
    - { source: "{{ src_relay }}" , destination: "{{ dest_relay }}" }

  - name: Hashins Postfix Configuration
    command: postmap hash:{{ item }}
    with_items:
    - "{{ dest_pass }}"
    - "{{ dest_relay }}"
