- hosts: "{{ target_hosts }}"
  remote_user: #Put Your Username here
  become: true

  vars:
  - ansible_ssh_user: #Put Your Username here
  - ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  
  vars_files:
  - "roles/{{ role_name }}/defaults/main.yml"
  
  tasks:
  - include: "roles/{{ role_name }}/tasks/restart.yml"
    when: ("{{ run_option }}" == "restart")
    
  - include: "roles/{{ role_name }}/tasks/start.yml"
    when: ("{{ run_option }}" == "start")
    
  - include: "roles/{{ role_name }}/tasks/stop.yml"
    when: ("{{ run_option }}" == "stop")
