- include: stop.yml

- name: Removing Kafka Directories
  file: 
    path: "{{ item }}"
    state: absent  
  with_items:
  - "{{ kafka_home }}"

- name: Removing Kafka and Zookeeper Services
  file:
    path: "/lib/systemd/system/{{ item }}"
    state: absent
  with_items:
  - "kafka.service"
  - "zookeeper.service"
  
- name: Removing Users
  user:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
  - "kafka"
