---
# Kafka configuration
kafka_version: "3.1.0"
kafka_dist: "kafka_2.13-{{ kafka_version }}.tgz"
kafka_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/{{ kafka_dist }}"

kafka_port: 9092
kafka_port_ssl: 9093
kafka_port_sasl: 9094

kafka_config_dir: "{{ base_dir }}/kafka/config"
kafka_bin_dir: "{{ base_dir }}/kafka/bin"
kafka_log_dirs: "{{ data_dir }}/kafka-logs"

# Broker IDs will be assigned based on inventory order
kafka_broker_ids:
  - { host: "kafka1.example.com", id: 1 }
  - { host: "kafka2.example.com", id: 2 }
  - { host: "kafka3.example.com", id: 3 }

# Security
kafka_tls_keystore_password: "changeit"
kafka_tls_truststore_password: "changeit"
kafka_sasl_jaas_config: |
  org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="admin" \
  password="admin-secret" \
  user_admin="admin-secret" \
  user_alice="alice-secret";
