---
# Zookeeper configuration
zookeeper_version: "3.7.0"
zookeeper_dist: "apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
zookeeper_url: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/{{ zookeeper_dist }}"

zookeeper_client_port: 2181
zookeeper_peer_port: 2888
zookeeper_leader_port: 3888

zookeeper_data_dir: "{{ data_dir }}/zookeeper"
zookeeper_config_dir: "{{ base_dir }}/zookeeper/conf"
zookeeper_bin_dir: "{{ base_dir }}/zookeeper/bin"

# Ensemble configuration
zookeeper_servers:
  - { id: 1, host: "zk1.example.com" }
  - { id: 2, host: "zk2.example.com" }
  - { id: 3, host: "zk3.example.com" }

# Security
zookeeper_tls_keystore_password: "changeit"
zookeeper_tls_truststore_password: "changeit"
