---
  - name: Install Java
    apt: pkg=openjdk-8-jre state=present update_cache=true

  - name: Download Elastic Search
    get_url: url="https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb" dest=/tmp/

  - name: Install Elastic Search
    command: dpkg -i elasticsearch-1.7.2.deb chdir=/tmp/

  - name: Enabling Elastic Search @ Boot
#    command: update-rc.d elasticsearch defaults
    command: sudo systemctl enable elasticsearch

  - name: Copy Elastic Search Configuration
    template: src={{ src }} dest={{ dest }} backup=yes

  - name: Restart Elastic Search
    action: service name=nginx state=restarted enabled=true
