---
  - name: Install Varnish Dependencies
    apt: pkg=python-pycurl state=latest update_cache=yes
    tags: varnish

  - name: Add Varnish Key
    apt_key: url=http://repo.varnish-cache.org/debian/GPG-key.txt
    tags: varnish

  - name: Add Varnish Repository
    apt_repository: repo='deb https://repo.varnish-cache.org/debian/ trusty varnish-4.1' update_cache=yes
    tags: varnish

  - name: Update Cache
    apt: update_cache=yes

  - name: Install Varnish
    apt: pkg=varnish state=latest update_cache=yes
    ignore_errors: yes

  - name: Copy Varnish Configuration
    template: src={{ item.source }} dest={{ item.destination }} backup=yes
    with_items:
    - { source: "{{ src_default }}", destination: "{{ dest_default }}" }
    - { source: "{{ src_varnish }}", destination: "{{ dest_varnish }}" }

  - name: Restart Varnish
    service: name=varnish state=restarted
    ignore_errors: yes

  - name: Reload Varnish
    service: name=varnish state=reloaded
    ignore_errors: yes
